### PR TITLE
Add chapter 5 of Rethinking 2

### PR DESCRIPTION
**Pull request by canyon289**

### CODE REVIEW

**Comment by canyon289** [comment]
@aloctavodia @AlexAndorra Finished but I'm stuck on a couple things I could use help on. To do them one at a time.

Do you guys know how to do code example 5.19 to 5.21 in the book cleanly in PyMC3? There's two parts
* Putting two models under one model context
* Simulated counterfactuals in a particular order (In this case age -> Marriage rate first, then (Age, Marriage)

In overthinking 5.25 Richard shows how to do this using just plain arrays, which I am able to follow, but not sure if it's possible within Theano/PyMC3 framework

**Comment by aloctavodia** [comment]
What about this? 

```python
with pm.Model() as model:
    A = pm.Data('A', df.A)
    ## A -> D <- M
    a = pm.Normal('a', 0 ,0.2)
    bM = pm.Normal('bM', 0 ,0.5)
    bA = pm.Normal('bA', 0 ,0.5)
    sigma = pm.Exponential('sigma', 1)
    mu = a + bM*df.M + bA*A
    D = pm.Normal('D', mu, sigma, observed=df.D)

    aM = pm.Normal('aM', 0 ,0.2)
    bAM = pm.Normal('bAM', 0 ,0.5)
    sigma_M = pm.Exponential('sigma_M', 1)
    mu_M = aM + bAM * A
    M = pm.Normal('M', mu_M, sigma_M, observed=df.M)

    trace = pm.sample(1000)

with model:
    seq_A = np.linspace(-2, 2, 50)
    pm.set_data({'A': seq_A})
    pps = pm.sample_posterior_predictive(trace, model=model)

_, ax = plt.subplots(1, 2)
ax[0].plot(seq_A, pps['D'].mean(0))
az.plot_hpd(seq_A, pps['D'], ax=ax[0])

ax[1].plot(seq_A, pps['M'].mean(0))
az.plot_hpd(seq_A, pps['M'], ax=ax[1])
```

**Comment by canyon289** [comment]
Wow....... How did you get that to work? Youre amazing. I swear I tried that but it didnt work but yet here it is. Thank you

image

**Comment by ColCarroll** [comment]
I don't know why reviewnb didn't pipe up, but can y'all see this? https://app.reviewnb.com/pymc-devs/resources/pull/73/

**Comment by AlexAndorra** [comment]
<p>As a former US president would say: yes, we can -- at least I can</p><p> </p>

**Comment by canyon289** [comment]
Aside from 5.39 where I'm getting different results from the book for some reason ready for review!  

Not sure if the different results are from the QuadPotential method  from MCMC inference

**Comment by AlexAndorra** [comment]
This is really nice work, thank you @canyon289 ! Especially when considering that there is a lot of new content in this chapter compared to the 1st edition.
I tried to add useful and clear comments, but please tell me if you have any question. 
Just one last comment: don't forget to run [black_nbconvert](https://github.com/dfm/black_nbconvert) on the NB when it's finalized 😉

**Comment by AlexAndorra** [comment]
Thanks for the new version @canyon289 ! I just left a few comments above but I think this is almost ready to merge 🎉 
Before merging, don't forget to run [black_nbconvert](https://github.com/dfm/black_nbconvert) on the NB 😉 
Just two notes, for this or future NBs:
- If you want to get rid of the `FutureWarning`s, you can do:
```python
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
```
- You can add `;` after plots to get rid of matplotlib axes

**Comment by AlexAndorra** [comment]
Ooh I also forgot: don't forget to add the last `watermark` cell, as Osvaldo did for the first three chapters

**Pull request merged**
