### PR TITLE
Chapter 9 of Statistical Rethinking 2nd Edition

### PR DESCRIPTION
**Pull request by oscarbranson**
Mangled the last one (#89) so badly that I created a new PR... hope this is better @aloctavodia!

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Hi @oscarbranson !
Did you have any questions about @aloctavodia's review or is everything clear?

**Comment by oscarbranson** [comment]
Thanks @aloctavodia  and @AlexAndorra - I haven't had time to look at it yet... I hope to get to it this weekend.

**Comment by AlexAndorra** [comment]
Hi @oscarbranson ! Do you think you'll have some time to move this across the finish line? 🏁

**Comment by oscarbranson** [comment]
Yes! Apologies for the delay, @AlexAndorra... I've been away. Should get to it early this week.

**Comment by AlexAndorra** [comment]
Let's move this one along: merging now, and when someone has time he can implement the changes @aloctavodia mentioned above 😉

**Comment by oscarbranson** [comment]
Apologies @AlexAndorra and @aloctavodia - it's been a hectic couple of months. I'll try to revisit this soon, but probably a good idea to merge for now - it mostly works as-is!

**Comment by aloctavodia** [comment]
Do not worry @oscarbranson we are living crazy times. And you already helped a lot! Thanks for your contributions.

**Pull request merged**
