### PR TITLE
Issues with Chapters 2 and 5

### PR DESCRIPTION
**Pull request by rpgoldman**
There seemed to me to be a number of issues here.  I addressed some cosmetic issues but some seem to require more thought:

1. The ArviZ plots that I tried to make really don't look good, and certainly don't come close to looking as good as the Seaborn ones. Can they be made better?
2. The model that is supposedly better for the rat tumor example in chapter 5 seems to have some real sampling issues, with many divergences appearing.

### CODE REVIEW

**Comment by rpgoldman** [comment]
I think I have all the requested changes in place.

An interesting thing I noticed: I could bump up the number of samples in the posterior predictive sampling because of using the vectorized form. Interestingly, if I put in the full amount of posterior samples for the line plots in the schools example, the plot became less persuasive, because it was a lot more "spiky." The 1000 sample plot looks like a best fit line plotted through the higher number of samples.  I suppose that means that the sampling is representative.

**Comment by rpgoldman** [comment]
I think this is ready to merge.

**Comment by rpgoldman** [comment]
<p>Made this change.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Adopted ArviZ settings.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Replaced with "Proper uninformative prior."  Hope that's right.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Fixed the style per request.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Fixed per this request.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>I'm not sure what's asked for here.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aloctavodia** [comment]
<p>Sorry for not being clear, I mean to use https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html instead of <code>pm.invlogit</code></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Interesting: if I plot with ArviZ I <em>do</em> get colors. Switching.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
I have pushed all the modifications requested for Chapter 2.  @aloctavodia Please check the one remaining discussion item for this notebook.

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Changed to "Proper noninformative prior."  Please check if this is ok.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>I'd rather not, since it's a better plot than the ArviZ alternative.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Plugged in that revision.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rpgoldman** [comment]
<p>done.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/81/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by aloctavodia** [comment]
Thanks a lot @rpgoldman for all your effort and help! Happy weekend!

**Comment by santiagoalonso** [comment]
I think that the reproduction of Table 5.3 and Figure 5.8b should be with posterior samples. Currently they are done with posterior predictive samples.

**Comment by aloctavodia** [comment]
Hi @santiagoalonso you are right, those figures represent posterior samples. Do you want to do a PR fixing this? If not, that's OK I can do it.

**Pull request merged**
