### PR TITLE
Chapter 14 of Rethinking 2

### PR DESCRIPTION
**Pull request by AlexAndorra**
Ready for review 🍾 
There is a lot of new material in this chapter. Most of these novelties are in sections 3 (instrumental variables), 4 (social relations models) and 5 (GPs), so I'd recommend focusing most of the reviewing efforts there.
Thanks in advance for the reviews 🖖

### CODE REVIEW

**Comment by canyon289** [comment]
Did a quick skim and things generally look good. Will do a deeper review this week, hopefully in next couple of days

**Comment by AlexAndorra** [comment]
<p>Indeed, this makes sense, thanks for catching this! Also, good to know we can parametrize the ExpQuad kernel with ls_inv!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/94/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Thanks for the review @aloctavodia ! I corrected the typos and implemented the changes on the GP for Oceanic tools model. It turns out that:

- the prior for `rhosq` is super important as there isn't a lot of data. I changed it from `Exponential(0.5)` (as in the book) to `HalfNormal(2)` and results are looking much closer to the book, as does the posterior for `rhosq`.
- I was using `Dmatsq` (squared distance) instead of `Dmat` (simple distance) to evaluate the GP.
- In posterior predictive plots, it looks like `etasq` and `rhosq` should **not** be squared: they are implicitly modeled as the square in the model -- notice that Richard doesn't square them [in his implementation](https://github.com/rmcelreath/rethinking/blob/f9c16bb7faec8a9883d976a769824b1764d12540/R/ulam_templates.R#L1363) of `cov_GPL2`. 
- Multiplying by 0.5 to make PPC plots look closer to the formula for ExpQuad kernel does improve the results -- note however that Richard doesn't do that in his implementation 🤷‍♂️ 

I think that there are subtle differences in the GP implementations between PyMC and ULAM that make a bijective match hard to get, but I think this looks quite good now!
If you agree with my changes, I'll rerun the whole NB and reformat it properly 🖖

**Comment by AlexAndorra** [comment]
@aloctavodia, as discussed I just pushed the change where `rhosq = pm.Deterministic("rhosq", 0.5 * ls_inv ** 2)`. This has the nice of property of recovering the exact formula for the ExpQuad kernel, but makes the results less similar as the book's.
This looks good enough to merge though, and we can refine the implementation even more later.
Also, I reran the whole NB 🖖

**Comment by aloctavodia** [comment]
There is a change to chapter 11's notebook that should not be part of this PR, right?

**Comment by AlexAndorra** [comment]
Yeah it should -- it's just a super tiny typo fix, so I figured it wasn't worth a dedicated PR. Thanks for approving --> merging! 🍾

**Pull request merged**
