### PR TITLE
Chapter 9 of Statistical Rethinking 2nd Edition

### PR DESCRIPTION
**Pull request by oscarbranson**
As I've done it today anyway (as mentioned in #67), I thought it was worth a PR... hope you don't mind, @nilichen!

Fairly straightforward chapter. Main stumbling block was the second row of Figure 9.6, although the code for this was not actually in the chapter, so this was a bonus anyway.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Hi @oscarbranson please clean this PR, you have included files from previous chapters.

**Comment by oscarbranson** [comment]
Sorry @aloctavodia - created a branch from the wrong point... I've never tried to do this before and have got myself in a real rebase tangle... Can you point me towards any good resources showing how to 'clean' a PR? Or should I just delete this one and start again?

**Comment by oscarbranson** [comment]
Closing this until I've cleaned it correctly.

**Comment by oscarbranson** [comment]
I mangled this so badly that I've created a new PR with only the relevant changes - now in #91

**Pull request closed without merging**
