### PR TITLE
Chapter 2 of BDA3

### PR DESCRIPTION
**Pull request by rosgori**
I would like to add this chapter to the main repository.

There are two examples in this chapter:

-  Example. Probability of a girl birth given placenta previa.
-  Estimating a rate from Poisson data: an idealized example.

I have used `pymc3` to reproduce the results. If anyone has suggestions (either code or English), I'd like to hear them!

### CODE REVIEW

**Comment by aloctavodia** [comment]
LGTM! Thank you for this PR! A couple of nitpicks, there is no need to write `plt.show()`, PyMC3 has a triangular distribution could you use it? 

the last one is a general doubt I hav and is not restricted to this PR. Should we use fstrings? I love them but that means the code only will run with Python >3.6

**Comment by rosgori** [comment]
Ok, I have deleted the lines with `plt.show()` and I have not used f-strings. The custom distribution is

```python
def triangular(central_num, width):
    
    left_num = central_num - width
    right_num = central_num + width
    theta = pm.Triangular('theta', lower=left_num, upper=right_num, c=central_num)
    
#     Comment these lines to see some changes
    if tt.lt(left_num, theta):
        theta = pm.Uniform('theta1', lower=0, upper=left_num)
    if tt.gt(right_num, theta):
        theta = pm.Uniform('theta2', lower=right_num, upper=1)
        
    return theta 
```

I have not changed a line in the code, although the result (the mean of the posterior distribution) is different if you comment those lines.

**Comment by aloctavodia** [comment]
LGTM!

**Comment by rosgori** [comment]
Done.

**Comment by aloctavodia** [comment]
Thanks @rosgori

**Pull request merged**
