### PR TITLE
Update Case Studies NBs for BCM

### PR DESCRIPTION
**Pull request by AlexAndorra**
Updates NBs for the Case Studies folder of BCM, as discussed in #36
This (painful) PR is now ready for review 🍾

### CODE REVIEW

**Comment by AlexAndorra** [comment]
@junpenglao and @aloctavodia I can't update `SignalDetectionTheory.ipynb` yet because it uses `heit_rotello.RData` and I don't have R on my laptop.
If one of you has R installed, can you convert this R file into `.csv` or `.txt` please ? I think it's the good thing to do to make this port even more usable.
Thanks in advance, and tell me if you have any questions!

**Comment by canyon289** [comment]
Yep, I'll do it by tonight max(16 hours)

**Comment by canyon289** [comment]
I realized I misread the comment and you weren't asking me but I'll do so anyway :D

If you're feeling like you want a challenge you could spin up an R docker container and do it yourself ;) But otherwise can you add a link to the .r file and I'll do it on my computer

**Comment by AlexAndorra** [comment]
Ooh you're right, that could be fun! Let me try to do that then and I'll keep you posted 😉

**Comment by canyon289** [comment]
The arviz docker container file in `./scripts` has all the commands you need! you can either mount your local file system or copy a file to and from the running container. Mounting is easier imo but do what you like!

**Comment by AlexAndorra** [comment]
@canyon289 I managed to build and lauch an R Docker container (after some head scratching TBH), but I'm running into an issue when trying to load the file:
```R
> load("/heit_rotello.RData")
Error in load("/heit_rotello.RData") :
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘heit_rotello.RData’ has magic number '"cond'
  Use of save versions prior to 2 is deprecated
```
After Googling, it seems to mean that the file was not saved properly. Unfortunately, I don't know the book, the data and R enough to solve that in a reasonable amount of time. So it'd be great if you or someone else could convert this R file into `.csv` or `.txt` 🙏  
I'll be happy to update the NB afterwards. Thanks a lot!

_PS: Note for the future: always save the files to **universal** file formats_

**Comment by aloctavodia** [comment]
@AlexAndorra I will send you the data in CSV format

**Comment by AlexAndorra** [comment]
Thanks for the files Osvaldo! They are now updated.
Trying to updated the `SignalDetectionTheory` NB though, I got a super weird error in the terminal: `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file` -- this appears when sampling a PyMC model and makes sampling hanging indefinitely around 75%.
If someone knows what this is about and / or can run the NB without issue I'm all ears!
PyMCheers 🖖

**Comment by AlexAndorra** [comment]
I suggest merging this next week -- potential fixes can go on subsequent PRs.

**Pull request merged**
