### PR TITLE
Fix typos in Chapter 4 Rethinking

### PR DESCRIPTION
**Pull request by canyon289**
Fixed a couple of things
* Some word misspellings in markdown
* Some variables with the word weight were spelled weigth
* Added some filters for warnings

### CODE REVIEW

**Comment by aloctavodia** [comment]
I have a problem with words ending in "ght", haha. Thanks for fixing that. I am not sure I like the _filters for warnings_ @junpenglao?

**Comment by junpenglao** [comment]
It is a lot of them? I would prefer not to turn them off as we might missed some `DeprecationWarning` when we rerun notebooks in the future.

**Comment by canyon289** [comment]
It's enough to where I can't disagree with your concern. I can turn them back on. The reason I didn't like them is because they leak my computer configuration but when I get back home I'll have access to my vms and will rerun the notebook in one of those.

I'm sort of paranoid about cybersecurity :(

**Comment by junpenglao** [comment]
it's a good habit to be paranoid ;-)

**Pull request closed without merging**
