### PR TITLE
Chapter 7 of BDA3

### PR DESCRIPTION
**Pull request by rosgori**
I would like to add this chapter to the main repository. There is one example in this chapter that has data:

- Example. Estimating a population total under simple random sampling using transformed normal models.

I have used pymc3 to reproduce the results. If anyone has suggestions (either code or English), I'd like to hear them!

By the way, I have some doubts about some calculations, specially about finding `y_mis` on page 188 and page 189.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Hi @rosgori, overall LGTM. I have one question, Why you compute `y_miss_1` the way you do instead of simple using `pm.sample_posterior_predictive`?  It seems to me you should use `pm.sample_posterior_predictive`, notice that this function has also a `size` parameter.

**Comment by rosgori** [comment]
Yes, I see that the other way of finding `y_miss_1` is 

```python
with model_1:
    ppc_1 = pm.sample_posterior_predictive(trace_1, samples=100, vars=[y_bar, mu, sigma])

y_miss_1 = np.mean(ppc_1['y_bar'], axis=1)
``` 
That avoids some calculations I am doing; I think I will modify some of them. 

Both methods show similar intervals.

**Comment by aloctavodia** [comment]
BTW, you do not need to pass `vars=[y_bar, mu, sigma]` by default you will get samples from `y_bar`

**Comment by aloctavodia** [comment]
Hi @rosgori, any update about this?

**Comment by rosgori** [comment]
Well, I think everything is okay. Although I don't know if I have to make some changes...

**Comment by aloctavodia** [comment]
ohh sorry for the misunderstanding I was waiting for you to change  the computation of `y_miss_1` before merging.

**Comment by rosgori** [comment]
I have added something...

Is it okay?

**Comment by aloctavodia** [comment]
Thanks @rosgori!

**Pull request merged**
