### PR TITLE
fixed posterior covariance calculation of Code 13.15, closes #53

### LINKED ISSUE #53: Chapter 13 posterior covariance in Code 13.15
This issue is in regard to the code of book Statistical Rethinking A Bayesian Course

The calculation of the posterior covariance in Code 13.15 does not agree with the calculation shown in the book (page 396). This is because in the current implementation `L_chol` is calculated as an upper triangular matrix and not a lower one as in the model (`m_13_1`) specification. The calculation might be clearer if it's done using `pm.expand_packed_triangular` (as used with `m_13_1`). 

I've run the following code in the place of Code 13.15 in the notebook to compare all three (book, current Code 13.15 implementation, and using `pm.expand_packed_triangular` )

```python
plt.rcParams.update({'font.size': 14})
# from the model
chol_model = pm.expand_packed_triangular(2, trace_13_1['chol_cov'].mean(0),lower=True).eval()
cov_model = np.dot(chol_model, chol_model.T)
# from the book
sa_est = trace_13_1['sigma_cafe'].mean(0)[0]
sb_est = trace_13_1['sigma_cafe'].mean(0)[1]
rho_est = trace_13_1['Rho'].mean()
cov_ab = sa_est * sb_est * rho_est
cov_book = np.array([sa_est**2, cov_ab, cov_ab, sb_est**2]).reshape(2,2)
# compute posterior mean bivariate Gaussian
Mu_est = trace_13_1['ab'].mean(axis=0)
Chol_cov = trace_13_1['chol_cov'].mean(axis=0)
L_chol = np.zeros((2, 2))
L_chol[np.triu_indices(2, 0)] = Chol_cov
Sigma_est = np.dot(L_chol, L_chol.T)
# draw contours
_, ax = plt.subplots(1, 1, figsize=(10, 10))
for ls, cov_ in zip(['-','--',':'],[Sigma_est, cov_model, cov_book]):
    Gauss2d(Mu_est, np.asarray(cov_), [0.1, 0.3, 0.5, 0.8, 0.99], ax=ax, ls=ls)
ax.scatter(a1, b1)
ax.scatter(a2, b2, 
           facecolors='none', edgecolors='k', lw=1)
ax.plot([a1, a2], [b1, b2], 'k-', alpha=.5)
ax.set_xlabel('intercept', fontsize=14)
ax.set_ylabel('slope', fontsize=14)
ax.set_xlim(1.5, 6.1)
ax.set_ylim(-2.5, 0);
```

comparison

Note that I modified the code in `Gauss2d` to accept an argument `ls` to control for the linestyle of the eclipse contours:
```python
def Gauss2d(mu, cov, ci, ax=None, ls='-'):
    """Copied from statsmodel"""
    if ax is None:
        _, ax = plt.subplots(figsize=(6, 6))

    v_, w = np.linalg.eigh(cov)
    u = w[0] / np.linalg.norm(w[0])
    angle = np.arctan(u[1]/u[0])
    angle = 180 * angle / np.pi # convert to degrees

    for level in ci:
        v = 2 * np.sqrt(v_ * chi2.ppf(level, 2)) #get size corresponding to level
        ell = Ellipse(mu[:2], v[0], v[1], 180 + angle, facecolor='None',
                      edgecolor='k',ls=ls,
                      alpha=(1-level)*.5,
                      lw=1.5)
        ell.set_clip_box(ax.bbox)
        ell.set_alpha(0.5)
        ax.add_artist(ell)
    
    return ax
```

### PR DESCRIPTION
**Pull request by chdamianos**
Closes issue #53 by modifying the calculation of `L_chol` in section `Code 13.15` from `L_chol[np.triu_indices(2, 0)] = Chol_cov` to `L_chol[np.tril_indices(2, 0)] = Chol_cov`. This modification corrects `L_chol` to a lower triangular matrix of the Cholesky decomposition and not an upper triangular matrix.

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Thank you, that's well spotted! 
And I agree with you  (#53 ): maybe we should seize on this PR to change the way we compute back the covariance matrix from the trace. 
Your proposal with `pm.expand_packed_triangular` is elegant and PyMC3onic. 
Your second proposal (doing as in the book) is more pedagogical though, as it shows the details of the computation. 
So I don't have a set preference here on what to do. What do you think @aloctavodia ?

**Comment by chdamianos** [comment]
@AlexAndorra I agree that `pm.expand_packed_triangular` is easier to read, also taking into account that this was the way the model was defined. On the other hand, as you mentioned, in it's current implementation it makes the reader think a bit more on how the Cholesky decomposition is used to calculate the covariance. Also using `np.tril_indices` is more consistent with the rest of code. I'm leaning towards `np.tril_indices` for consistency.

**Comment by AlexAndorra** [comment]
Yeah I get your point. However, if we're not going with `pm.expand_packed_triangular` I think doing the computation like in the book would be better than sticking with the current implentation: I find it clearer to the user, more pedagogical and consistent with the spirit of this whole repo (staying as close to the book as possible).

**Comment by chdamianos** [comment]
OK that makes sense. I've changed the calculation to make use of `pm.expand_packed_triangular`. I also supressed `FutureWarning` because I thought it was making the notebook a bit difficult to read.

As a first time reader I think it would benefit me to have seen one or two examples of using the `pm.LKJCorr` prior, instead of `pm.LKJCholeskyCov` for the covariance, which would be closer to the code examples in the book. After I finish the book I might have a go adding an example with `pm.LKJCorr`.

**Comment by AlexAndorra** [comment]
Thank you, LGTM now!

I don't know exactly but I think `pm.LKJCholeskyCov`was prefered to `pm.LKJCorr` for computation efficiency reasons. That being said, I think you're right, one or two examples of how to use the correlation prior could be useful to readers. I can help you with that later if you need :)

And about the `FutureWarning`, do you know where it comes from? I have the same annoying message but I'd like to get rid of it entirely instead of just hiding it.

**Comment by chdamianos** [comment]
I'm under the same impression about using `pm.LKJCholeskyCov`. Numerically it make sense to be more efficient to work with an upper triangular matrix (L) than the whole covariance matrix. Thanks for offering help! If I try to get some code examples working with `pm.LKJCorr` I'll be very happy to collaborate. 

The warnings are a mystery for me at the moment but I think are the same as in this Theano issue discussed here https://github.com/Theano/Theano/issues/6695

**Comment by lucianopaz** [comment]
I just wanted to chime in about the future warnings. I managed to track them down in [this issue](https://github.com/Theano/Theano/issues/6667), but I didn't see an immediate fix at the time.

**Comment by AlexAndorra** [comment]
Oh ok, thanks Luciano, that's good to know!

**Comment by AlexAndorra** [comment]
FYI @chdamianos `pm.LKJCorr` [seems faulty and may be deprecated](https://github.com/pymc-devs/pymc3/issues/3473) - while `pm.LKJCholeskyCov` is right

**Comment by chdamianos** [comment]
thanks @AlexAndorra for the heads up! Yes it looks like `pm.LKJCholeskyCov` is the safest prior for covariance matrices.

**Comment by AlexAndorra** [comment]
Does anyone with write access see why there is a conflict with PR? 
@chdamianos are you sure you based this on the latest master?

**Comment by chdamianos** [comment]
@AlexAndorra thanks for the heads up. It looks like the notebook has been updated since my pull request. I will pull latest master and update

**Comment by chdamianos** [comment]
@AlexAndorra I rebased to latest master. It should be ok now.

**Comment by junpenglao** [comment]
Could you also please rerun the notebook from the latest PyMC3 release?

**Comment by chdamianos** [comment]
@junpenglao good catch, it's now run with the latest release

**Comment by junpenglao** [comment]
Thanks!

**Pull request merged**
