### PR TITLE
Add chapter 11 of Rethinking 2

### PR DESCRIPTION
**Pull request by AlexAndorra**
**Ready for review**.
There are two main points of attention:

1. The scientific model of the number of tools for the Pacific Islands (page 356 in book, cell `Code 11.49` in notebook) runs smoothly but makes terrible predictions, especially for high-contact islands. I suspect it's because the `b` coefficient for high contact societies is unidentifiable at high population ranges (because there are no samples), but I tried a bunch of different Exponential and HalfNormal priors for this parameter and nothing seems to work. The weird thing is that I think I used the same parametrization as the book.

2. The first multinomial model behaves weirdly and doesn't replicate the book's results -- possible bug? I added more comments in the notebook.

Thanks a lot for the reviews ✌️ I'll re-run the whole NB once we've fixed all the issues.

### CODE REVIEW

**Comment by AlexAndorra** [comment]
@aloctavodia and @canyon289 I found a way to improve the scientific model of Oceanic tools 🎉 
I used a different trick to scale the population data, and it seems to work -- although I'm not sure why the difference is so big compared to the previous method 🤷 
I would very much appreciate @junpenglao's opinion on this, to make sure we didn't miss something -- see the PR's description for more details or tell me if you have questions. And a big thank you in advance!

**Comment by AlexAndorra** [comment]
- Blackified the code and adressed @aloctavodia's and @canyon289's comments -- about the ArviZ warning, I chose not to add one dimension, as it clutters the code and it probably comes from a bug. Once this bug is resolved I can rerun the NB.

- I solved the problem with the first Multinomial model by taking the first category as pivot instead of the last one (as the last one is very probable compared to the others, it switches the sign of the slope when taken as the pivot). However, this is still a mystery to me why this works in the book -- is it a typo in the book or a bug on PyMC3? 🤷‍♂️ I think we can merge, but maybe we'll have to revisit that.

If all this is good for you, I think this is ready to merge 🎉

**Comment by aloctavodia** [comment]
It will be a good idea to open issues so we do not forget about this stuff.

**Comment by AlexAndorra** [comment]
True, but I don't know if these are still open issues: maybe what I did solved the problems 🤷‍♂️ I'm counting on the community's peer-reviewing to find out 😅

**Pull request merged**
