### PR TITLE
started Ch 11 EOC solutions

### PR DESCRIPTION
**Pull request by benslack19**
Hello, this is my first commit to the Rethinking_2 end of chapter problems. It's a modest addition. I started Chapter 11, doing the first two problems but I can add others later. I welcome contributions.

I saw the suggestion about a pre-commit check but I did not see this file. Nevertheless, I used Ch 9 as a template so I think formatting and style issues should be minimal.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
> I saw the suggestion about a pre-commit check but I did not see this file

Here you go https://github.com/pymc-devs/pymc/wiki/PyMC3-Jupyter-Notebook-Style-Guide

---

These solution look good - do you want to add the rest of the `E` exercises?

**Comment by MarcoGorelli** [comment]
content looks good, looks like there's still some linting failures though

**Comment by benslack19** [comment]
<p>OK the replacement should be showing up now</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/resources/pull/166/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by benslack19** [comment]
hope linting failures are also resolved now?

**Review by MarcoGorelli — APPROVED** [review]

**Comment by benslack19** [comment]
yay!

**Pull request merged**
