### PR TITLE
Answers chapter 14 exercises

### PR DESCRIPTION
**Pull request by AlexAndorra**
Here is the final chapter, ready for review 🎉 

Just note I had to use `pm.compare` instead of `az.compare` in problem 14M2. When ArviZ implements multiple-likelihood models I'll update this NB, as discussed with @aloctavodia

I'm here for any edit 😉 
PyMCheers!

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Did someone get some time to review this PR?

**Comment by aloctavodia** [comment]
I will, sorry for the delay.

**Comment by aloctavodia** [comment]
Thanks @AlexAndorra! And sorry about the delaaaaaaaayyyyyyyyyy

**Comment by AlexAndorra** [comment]
🎉 🎉 🎉 
Thanks for the review Oslvado!

**Pull request merged**
