### PR TITLE
Rethinking_2 Chp_03: add seed, fix typo

### PR DESCRIPTION
**Pull request by joannadiong**
I added a seed to the Chp 3 notebook as per the [PyMC Notebook style](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style), and updated the `ax.imshow()` origin keyword to `lower`. Notebook has been re-compiled. 

Another small PR. Cheers.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
cool, thanks!

**Comment by AlexAndorra** [comment]
Any reason this was closed? I don't see any problem with it

**Comment by aloctavodia** [comment]
I think @joannadiong accidentally included in this PR a change already merged in a previous PR. @joannadiong let us know if you need help with git/github. We know it can be very tricky!

**Comment by joannadiong** [comment]
Hi @MarcoGorelli, I appear to have mistaken a Chp 4 change for Chp 3. So Chp 3 changes are only the seed and a typo. I will update the Issue title for clarity but leave intact the orignal comment message.

To @AlexAndorra and @aloctavodia, not sure, but I may have accidentally closed the Issue when the branch I was working on was deleted. Apologies. In future, should branches be deleted only after Issues are closed by a maintainer?

Yes please, Git/GitHub refs especially for contributor standard practice would be great. Thank you.

**Comment by MarcoGorelli** [comment]
Cool, thanks for explaining - I think this is fine then

Re-git: I think the first 3 chapters of [this book](https://git-scm.com/book/en/v2) do a really good job of teaching you the fundamentals

**Comment by joannadiong** [comment]
Thanks @MarcoGorelli for the ref -- it's a good book. 

Happy for you to merge the small edits and close the PR. _Then_ I will delete the branch.  Cheers

**Review by MarcoGorelli — APPROVED** [review]

**Pull request merged**
