### PR TITLE
Apply nbqa black to all Rethinking_2 notebooks

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Sorry it's taken me a while to get round to this - perhaps the easiest thing here is to do one folder per PR? If so, here's Rethinking 2

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
:thinking: not sure why the github action isn't starting

**Comment by AlexAndorra** [comment]
Mmmh yeah, that's weird 🤨 
@canyon289 do you know if we need to enable something for GH Actions? Marco already set up all the config files in a previous PR, so it should work already I guess

**Review by AlexAndorra — APPROVED** [review]
All good, thanks @MarcoGorelli ! I guess I should wait for GH Actions to start and pass before merging?

**Comment by MarcoGorelli** [comment]
> All good, thanks @MarcoGorelli ! I guess I should wait for GH Actions to start and pass before merging?

Thanks! 

I guess that would be better, but I can't tell why it's not starting

**Comment by MarcoGorelli** [comment]
@AlexAndorra judging by what I've seen in PyMC-examples, the GitHub action should get activated after you've merged

**Comment by AlexAndorra** [comment]
Aha, good to know! Merging then 🎉 Thanks Marco!

**Pull request merged**
