### PR TITLE
Rethinking 2, Chapter 4, Code 4.39, initialise x to range of weights

### PR DESCRIPTION
**Pull request by madian44**
I noticed that the plots for code 4.39 and 4.40 did not match the plots in the book.

I have initialised 'x' to hopefully reflect the 'R' code in the book.

I have run the pre-commit checks.

Is it preferable to submit a pull request with a notebook containing the generated output?

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @madian44 - yes, if the code changes the output then I think it'd be better to re-run the notebook (I think most of the ones in this folder are quite fast to run anyway)

**Comment by madian44** [comment]
I've updated the output in notebook

**Comment by madian44** [comment]
Fixed conflicts with master

**Review by MarcoGorelli — APPROVED** [review]
Well spotted, thanks @madian44 !

**Review by MarcoGorelli — APPROVED** [review]

**Pull request merged**
