### PR TITLE
Add code for subsection 16.2

### PR DESCRIPTION
**Pull request by ricardoV94**
Working code for the subsection 16.2 of chapter 16

I tried to write the model in a way that makes it very comparable to the STAN code.
I am open to suggestions on how to improve it, if you think that is needed.

Linking to #67

(I apologize for deleting the previous pull request and reopening this one, but I realized I had not created a separate branch and as such I could not do independent PRs for other issues :/ )

### CODE REVIEW

**Comment by ccaprani** [comment]
It's a pity these PRs are not being merged - now there are two Chap 16 files, this and #118 . @ricardoV94 we should combine?

**Comment by ricardoV94** [comment]
@ccaprani, I am not sure what is the most practical way forward.

If you are comfortable with my code to make changes that might arise during review, feel free to merge it with your notebook. Otherwise, we can wait until both notebooks are reviewed, and only then merge them.

**Comment by ccaprani** [comment]
Shameless call out to @aloctavodia or @AlexAndorra to advise ;-)

**Comment by aloctavodia** [comment]
We can merge #118 first and then @ricardoV94 you can send a new PR adding section 16.2 to that. Is that OK?

**Comment by ricardoV94** [comment]
Sounds good to me

**Comment by ccaprani** [comment]
I see Richard McElreath is starting to teach his 
[Statistical Rethinking course](https://github.com/rmcelreath/stat_rethinking_2020#calendar--topical-outline) and suggesting python/pymc3. Can these be merged? Thanks!

**Comment by aloctavodia** [comment]
Sorry for all the delays. I merged #118, this can not be added to that.

**Comment by ccaprani** [comment]
Thank you @aloctavodia! @ricardoV94 - are you good to merge? Let me know if I can help. Cheers.

**Comment by ricardoV94** [comment]
I will do another PR so that it can be merged

**Comment by ricardoV94** [comment]
@ccaprani It should be good to go now.

**Comment by aloctavodia** [comment]
Thanks @ricardoV94 and sorry about the delays.

**Comment by ricardoV94** [comment]
@aloctavodia No problem :)

**Pull request merged**
