### PR TITLE
Fix bugs in BDA3/chap_03.ipynb due to API changes

### PR DESCRIPTION
**Pull request by xieyj17**
Hi, I am new to PyMC, and I am not sure how much change has been made since this notebook was published. It seems not working with current version of PyMC3, and here are the changes I made:

1. Change to `arviz` for plotting.
2. Remove `nuts_kwargs={'target_accept':0.95}`  as it's not working (block 8)
3. In block 11, `varnames` -> `var_names`
4. In block 29, `pm.diagnostics.effective_n` is no longer available. Replace it with `ess_bulk` and `ess_tail`.
5. In block 34, `pm.sample_ppc` is no longer available, replace it with `pm.sample_posterior_predictive` .
6. In block 46, `pm.pairplot` is no longer available, replace it with `az.plot_pair`.

Please let me know if it looks good to you.

### CODE REVIEW

**Comment by canyon289** [comment]
@xieyj17 Thank you for this contribution! All good from my review and lets wait for the precommit check to see what its assessment is!

**Comment by canyon289** [comment]
It seems that the precommit script needs to be run. Do one of the methods listed here work for you?

https://stackoverflow.com/questions/48301280/how-to-manually-run-a-git-pre-commit-hook-without-attempting-a-commit

**Comment by xieyj17** [comment]
Hi @canyon289 , I have run `pre-commit run --all-files` and now they all show `passed`. Please let me know if that would work? Thank you!

**Comment by canyon289** [comment]
@xieyj17 Looks great! Merging (Apologies for the delay)

**Pull request merged**
