### PR TITLE
Added Fig 8.2, updated Figs 8.3, 8.4, package update, small debugs

### PR DESCRIPTION
**Pull request by jankaWIS**

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Thanks for the PR @jankaWIS !
Unfortunately, it looks like there are conflicts in your NB:
```python
<<<<<<< Updated upstream
   "execution_count": 1,
   "execution_count": 1,
   "metadata": {
   "metadata": {
    "ExecuteTime": {
    "ExecuteTime": {
     "end_time": "2020-08-22T22:19:29.820750Z",
     "end_time": "2020-08-22T22:19:29.820750Z",
     "start_time": "2020-08-22T22:19:28.239050Z"
     "start_time": "2020-08-22T22:19:28.239050Z"
    }
    }
   },
   },
=======
   "execution_count": 17,
   "metadata": {},
>>>>>>> Stashed changes
```
which makes it impossible to review 😕 
Can you resolve the merge conflict and push again?

**Comment by jankaWIS** [comment]
Hups, sorry, I hope now it's correct :). Thanks for pointing it out (although I am surprised since it told me it has no conflicts when I opened it..)

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Thanks for the PR @jankaWIS ! This does improve a bunch of outputs 👍 
However, there are changes that are not necessary and make the code less readable IMO (see my comments below). 
Once this is done, please make sure you're following the [PyMC NB style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style/3a92c230b9dc8896d6c82a32f4ce25f8d9e73191), and then it should be ready 👌

**Review by AlexAndorra — APPROVED** [review]
Looking all good now, thanks for the contribution @jankaWIS !

**Pull request merged**
