### PR TITLE
Implement NB formatting pre-commit checks in CI 

### LINKED ISSUE #120: Implement NB formatting pre-commit checks in CI
**This issue is up for grabs**

That'd be great to implement here the automatic formatting checks we do on NBs on the main PyMC3 repo.
This means using using `isort` and `black` via the [`nbqa` package](https://github.com/nbQA-dev/nbQA) to get a consistent codebase and allow maintainers to focus on substance instead of style while reviewing PRs. 

Ideally, we would have the same process as outlined in the [PyMC style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC's-Jupyter-Notebook-Style) and could therefore refer contributors to it.

Tagging you here @MarcoGorelli, because you know about this, so if you feel like implementing this, that'd be awesome!

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #120 

Virtually the same config as there is in PyMC3

Rather that setting up a GitHub action to run this, I think it would be a good chance to enable pre-commit-ci here (see [here](https://twitter.com/HEPfeickert/status/1324823925898027008) for a comment from a very enthusiastic user), which you can do at https://results.pre-commit.ci/

----

running `black` produces a huge number of changes, and sometimes requiring skipping code...how about an initial PR like this to get `pyupgrade` and `isort` in, and then a follow-up one which applies `nbqa black` to 5 notebooks per commit?

### CODE REVIEW

**Comment by canyon289** [comment]
Sounds good to me. Im going to merge before theres a conflict!

**Comment by AlexAndorra** [comment]
Thanks a lot @MarcoGorelli, this is really great 🎉 

> Rather that setting up a GitHub action to run this, I think it would be a good chance to enable pre-commit-ci here

To make sure I understand, what does this mean concretely? The CI is run by pre-commit instead of GH? And does this automatically apply isort/black/pyugrade now when the checks fails?

> running black produces a huge number of changes, and sometimes requiring skipping code...how about an initial PR like this to get pyupgrade and isort in, and then a follow-up one which applies nbqa black to 5 notebooks per commit?

Perfect, sounds good 👍 You can even do only one PR where each commit is refactoring 5 NBs, as we did for the last such PR on the main PyMC repo 😉

**Comment by MarcoGorelli** [comment]
> The CI is run by pre-commit instead of GH? And does this automatically apply isort/black/pyugrade now when the checks fails?

**Comment by MarcoGorelli** [comment]
> The CI is run by pre-commit instead of GH?

Yes, exactly - see [here](https://github.com/nbQA-dev/nbQA/pull/432) for an example, at the bottom of the PR in the 'checks' section there's one called "pre-commit.ci - pr"

> And does this automatically apply isort/black/pyugrade now when the checks fails?

Yes! See [here](https://github.com/nbQA-dev/nbQA/pull/381/commits) for an example - someone made a PR, but they had some trailing whitespace, so pre-commit-ci added an extra commit "[pre-commit.ci] auto fixes from pre-commit.com hooks "

**Comment by canyon289** [comment]
So if I get this right, lets say I commit and push a notebook with the imports out of order, the pre commit hook automatically changes the important order and makes a commit on github fixing it?

**Comment by MarcoGorelli** [comment]
that's right!

**Comment by canyon289** [comment]
A couple more question if you dont mind
Does the precommit hook happen `pre commit` locally? So in this case neither the local or the remote will ever "see" a notebook with imports out of order

Or explained another way, if I have a staged notebook with imports out of order, when I make a commit locally, the pre commit hook will automatically sort them, then make the commit locally?

**Comment by MarcoGorelli** [comment]
no worries, ask all you like :smile:

_locally_, if you enable pre-commit (`pre-commit install`), then pre-commit will apply the pre-commit hooks to any file which you stage and will only let you make a commit if all the pre-commit hooks pass.

However, if you open a pull request and you forgot to run `pre-commit` locally, then `pre-commit-ci` will add a commit on the remote fixing your files (to get this change locally, you would need to do `git pull` or `git fetch`)

**Comment by canyon289** [comment]
oh ok, did we add pre-commit-ci here, or just the local pre commit?

The reason I ask is because some people like me might not know that once pushed the files are going to get modified, so then we make a commit, push. then make another commit, and push, but the second time we get a merge conflict because a commit has been added on the remote.

And in particular with notebooks merge conflicts are horrible. Do you see that case happening here?

**Comment by MarcoGorelli** [comment]
This PR just adds pre-commit (local version). To enable pre-commit-ci, you need to install it from https://results.pre-commit.ci

> The reason I ask is because some people like me might not know that once pushed the files are going to get modified, so then we make a commit, push. then make another commit, and push, but the second time we get a merge conflict because a commit has been added on the remote.
>
> And in particular with notebooks merge conflicts are horrible. Do you see that case happening here?

In this case, I'd expected just running `pre-commit run` locally should be enough to resolve the conflicts, given that it'd do the same thing that pre-commit-ci would do. You can always try it and then disable it if it's disruptive

**Comment by canyon289** [comment]
Perfect! As long as it makes the changes locally then there should be more surprise merge conflicts! if this statement is correct then I see don't see this as disruptive, quite the opposite actually, it's super cool and will make life easier for everyone

**Pull request merged**
